{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Streamlit app"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting streamlit\n",
      "  Downloading streamlit-0.62.0-py2.py3-none-any.whl (7.1 MB)\n",
      "Collecting validators\n",
      "  Using cached validators-0.15.0.tar.gz (27 kB)\n",
      "Requirement already satisfied: pandas>=0.21.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (1.0.4)\n",
      "Requirement already satisfied: pillow>=6.2.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (7.0.0)\n",
      "Collecting protobuf>=3.6.0\n",
      "  Downloading protobuf-3.12.2-cp37-cp37m-win_amd64.whl (1.0 MB)\n",
      "Collecting astor\n",
      "  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)\n",
      "Requirement already satisfied: numpy in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (1.18.4)\n",
      "Requirement already satisfied: requests in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (2.22.0)\n",
      "Collecting boto3\n",
      "  Downloading boto3-1.14.9-py2.py3-none-any.whl (128 kB)\n",
      "Requirement already satisfied: tzlocal in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (2.1)\n",
      "Collecting base58\n",
      "  Using cached base58-2.0.1-py3-none-any.whl (4.3 kB)\n",
      "Collecting cachetools>=4.0\n",
      "  Using cached cachetools-4.1.0-py3-none-any.whl (10 kB)\n",
      "Collecting pydeck>=0.1.dev5\n",
      "  Using cached pydeck-0.4.0b2-py2.py3-none-any.whl (4.4 MB)\n",
      "Requirement already satisfied: python-dateutil in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (2.8.1)\n",
      "Requirement already satisfied: tornado>=5.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (6.0.3)\n",
      "Requirement already satisfied: packaging in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (20.1)\n",
      "Collecting botocore>=1.13.44\n",
      "  Downloading botocore-1.17.9-py2.py3-none-any.whl (6.3 MB)\n",
      "Collecting toml\n",
      "  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)\n",
      "Collecting altair>=3.2.0\n",
      "  Using cached altair-4.1.0-py3-none-any.whl (727 kB)\n",
      "Requirement already satisfied: click>=7.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (7.0)\n",
      "Requirement already satisfied: watchdog in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Collecting blinker\n",
      "  Using cached blinker-1.4.tar.gz (111 kB)\n",
      "Collecting enum-compat\n",
      "  Using cached enum_compat-0.0.3-py3-none-any.whl (1.3 kB)\n",
      "Requirement already satisfied: six>=1.4.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from validators->streamlit) (1.14.0)\n",
      "Requirement already satisfied: decorator>=3.4.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from validators->streamlit) (4.4.1)\n",
      "Requirement already satisfied: pytz>=2017.2 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from pandas>=0.21.0->streamlit) (2019.3)\n",
      "Requirement already satisfied: setuptools in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from protobuf>=3.6.0->streamlit) (45.2.0.post20200210)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from requests->streamlit) (1.25.8)\n",
      "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from requests->streamlit) (3.0.4)\n",
      "Requirement already satisfied: idna<2.9,>=2.5 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from requests->streamlit) (2.8)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from requests->streamlit) (2019.11.28)\n",
      "Collecting s3transfer<0.4.0,>=0.3.0\n",
      "  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)\n",
      "Collecting jmespath<1.0.0,>=0.7.1\n",
      "  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)\n",
      "Requirement already satisfied: ipykernel>=5.1.2; python_version >= \"3.4\" in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from pydeck>=0.1.dev5->streamlit) (5.1.4)\n",
      "Requirement already satisfied: jinja2>=2.10.1 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from pydeck>=0.1.dev5->streamlit) (2.11.1)\n",
      "Requirement already satisfied: traitlets>=4.3.2 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from pydeck>=0.1.dev5->streamlit) (4.3.3)\n",
      "Requirement already satisfied: ipywidgets>=7.0.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from pydeck>=0.1.dev5->streamlit) (7.5.1)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from packaging->streamlit) (2.4.6)\n",
      "Collecting docutils<0.16,>=0.10\n",
      "  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)\n",
      "Requirement already satisfied: entrypoints in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from altair>=3.2.0->streamlit) (0.3)\n",
      "Requirement already satisfied: jsonschema in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from altair>=3.2.0->streamlit) (3.2.0)\n",
      "Requirement already satisfied: toolz in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from altair>=3.2.0->streamlit) (0.10.0)\n",
      "Requirement already satisfied: pathtools>=0.1.1 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from watchdog->streamlit) (0.1.2)\n",
      "Requirement already satisfied: jupyter-client in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (5.3.4)\n",
      "Requirement already satisfied: ipython>=5.0.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (7.12.0)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from jinja2>=2.10.1->pydeck>=0.1.dev5->streamlit) (1.1.1)\n",
      "Requirement already satisfied: ipython-genutils in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from traitlets>=4.3.2->pydeck>=0.1.dev5->streamlit) (0.2.0)\n",
      "Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (3.5.1)\n",
      "Requirement already satisfied: nbformat>=4.2.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.0.4)\n",
      "Requirement already satisfied: importlib-metadata; python_version < \"3.8\" in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from jsonschema->altair>=3.2.0->streamlit) (1.5.0)\n",
      "Requirement already satisfied: attrs>=17.4.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from jsonschema->altair>=3.2.0->streamlit) (19.3.0)\n",
      "Requirement already satisfied: pyrsistent>=0.14.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from jsonschema->altair>=3.2.0->streamlit) (0.15.7)\n",
      "Requirement already satisfied: pyzmq>=13 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from jupyter-client->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (18.1.1)\n",
      "Requirement already satisfied: jupyter-core>=4.6.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from jupyter-client->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (4.6.1)\n",
      "Requirement already satisfied: pywin32>=1.0; sys_platform == \"win32\" in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from jupyter-client->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (227)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipython>=5.0.0->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (3.0.3)\n",
      "Requirement already satisfied: backcall in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipython>=5.0.0->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (0.1.0)\n",
      "Requirement already satisfied: colorama; sys_platform == \"win32\" in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipython>=5.0.0->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (0.4.3)\n",
      "Requirement already satisfied: pickleshare in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipython>=5.0.0->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (0.7.5)\n",
      "Requirement already satisfied: pygments in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipython>=5.0.0->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (2.5.2)\n",
      "Requirement already satisfied: jedi>=0.10 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from ipython>=5.0.0->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (0.14.1)\n",
      "Requirement already satisfied: notebook>=4.4.1 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (6.0.3)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from importlib-metadata; python_version < \"3.8\"->jsonschema->altair>=3.2.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: wcwidth in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (0.1.8)\n",
      "Requirement already satisfied: parso>=0.5.0 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel>=5.1.2; python_version >= \"3.4\"->pydeck>=0.1.dev5->streamlit) (0.5.2)\n",
      "Requirement already satisfied: terminado>=0.8.1 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.8.3)\n",
      "Requirement already satisfied: prometheus-client in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.7.1)\n",
      "Requirement already satisfied: nbconvert in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (5.6.1)\n",
      "Requirement already satisfied: Send2Trash in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (1.5.0)\n",
      "Requirement already satisfied: bleach in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (3.1.0)\n",
      "Requirement already satisfied: mistune<2,>=0.8.1 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.8.4)\n",
      "Requirement already satisfied: defusedxml in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.6.0)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (1.4.2)\n",
      "Requirement already satisfied: testpath in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.4.4)\n",
      "Requirement already satisfied: webencodings in c:\\users\\siyam\\anaconda3\\new folder\\lib\\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit) (0.5.1)\n",
      "Building wheels for collected packages: validators, blinker\n",
      "  Building wheel for validators (setup.py): started\n",
      "  Building wheel for validators (setup.py): finished with status 'done'\n",
      "  Created wheel for validators: filename=validators-0.15.0-py3-none-any.whl size=18376 sha256=6094833929df29e9223431ba42739c769e4da989b85ef680ace02c50c950d74b\n",
      "  Stored in directory: c:\\users\\siyam\\appdata\\local\\pip\\cache\\wheels\\ff\\a1\\08\\0650ea8df7821ecd87760d16213b53dd23403927a69a388268\n",
      "  Building wheel for blinker (setup.py): started\n",
      "  Building wheel for blinker (setup.py): finished with status 'done'\n",
      "  Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13455 sha256=ba93f2c061815591d261b70f2894c85a7516d681c2cb106e57c2d30375d8722f\n",
      "  Stored in directory: c:\\users\\siyam\\appdata\\local\\pip\\cache\\wheels\\22\\f5\\18\\df711b66eb25b21325c132757d4314db9ac5e8dabeaf196eab\n",
      "Successfully built validators blinker\n",
      "Installing collected packages: validators, protobuf, astor, docutils, jmespath, botocore, s3transfer, boto3, base58, cachetools, pydeck, toml, altair, blinker, enum-compat, streamlit\n",
      "  Attempting uninstall: docutils\n",
      "    Found existing installation: docutils 0.16\n",
      "    Uninstalling docutils-0.16:\n",
      "      Successfully uninstalled docutils-0.16\n",
      "Successfully installed altair-4.1.0 astor-0.8.1 base58-2.0.1 blinker-1.4 boto3-1.14.9 botocore-1.17.9 cachetools-4.1.0 docutils-0.15.2 enum-compat-0.0.3 jmespath-0.10.0 protobuf-3.12.2 pydeck-0.4.0b2 s3transfer-0.3.3 streamlit-0.62.0 toml-0.10.1 validators-0.15.0\n"
     ]
    }
   ],
   "source": [
    "#pip install pipenv\n",
    "\n",
    "!pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Streamlit dependencies\n",
    "import streamlit as st\n",
    "import joblib,os\n",
    "\n",
    "# Data dependencies\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Vectorizer\n",
    "news_vectorizer = open(\"Data/vectoriser-ngram-(1,2).pkl\",\"rb\")\n",
    "tweet_cv = joblib.load(news_vectorizer) # loading your vectorizer from the pkl file\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load your raw data\n",
    "raw = pd.read_csv(\"Data/train.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "  \n",
    "\"\"\"\n",
    "    Simple Streamlit webserver application for serving developed classification\n",
    "    models.\n",
    "    Author: Explore Data Science Academy.\n",
    "    Note:\n",
    "    ---------------------------------------------------------------------\n",
    "    Plase follow the instructions provided within the README.md file\n",
    "    located within this directory for guidance on how to use this script\n",
    "    correctly.\n",
    "    ---------------------------------------------------------------------\n",
    "    Description: This file is used to launch a minimal streamlit web\n",
    "    application. You are expected to extend the functionality of this script\n",
    "    as part of your predict project.\n",
    "    For further help with the Streamlit framework, see:\n",
    "    https://docs.streamlit.io/en/latest/\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "# The main function where we will build the actual app\n",
    "def main():\n",
    "    \"\"\"Tweet Classifier App with Streamlit \"\"\"\n",
    "\n",
    "    # Creates a main title and subheader on your page -\n",
    "    # these are static across all pages\n",
    "    st.title(\"Tweet Classifer\")\n",
    "    st.subheader(\"Climate change tweet classification\")\n",
    "\n",
    "    # Creating sidebar with selection box -\n",
    "    # you can create multiple pages this way\n",
    "    options = [\"Prediction\", \"Information\", \"Models\"]\n",
    "    selection = st.sidebar.selectbox(\"Choose Option\", options)\n",
    "\n",
    "    # Building out the \"Information\" page\n",
    "    if selection == \"Information\":\n",
    "        st.info(\"General Information\")\n",
    "        # You can read a markdown file from supporting resources folder\n",
    "        st.markdown(\"Some information here\")\n",
    "\n",
    "        st.subheader(\"Raw Twitter data and label\")\n",
    "        if st.checkbox('Show raw data'): # data is hidden if box is unchecked\n",
    "            st.write(raw[['sentiment', 'message']]) # will write the df to the page\n",
    "\n",
    "    # Building out the predication page\n",
    "    if selection == \"Prediction\":\n",
    "        st.info(\"Prediction with ML Models\")\n",
    "        # Creating a text box for user input\n",
    "        tweet_text = st.text_area(\"Enter Text\",\"Type Here\")\n",
    "\n",
    "        if st.button(\"Classify\"):\n",
    "            # Transforming user input with vectorizer\n",
    "            vect_text = tweet_cv.transform([tweet_text]).toarray()\n",
    "            # Load your .pkl file with the model of your choice + make predictions\n",
    "            # Try loading in multiple models to give the user a choice\n",
    "            predictor = joblib.load(open(os.path.join(\"Data/BNBmodel.pkl\"),\"rb\"))\n",
    "            prediction = predictor.predict(vect_text)\n",
    "\n",
    "            # When model has successfully run, will print prediction\n",
    "            # You can use a dictionary or similar structure to make this output\n",
    "            # more human interpretable.\n",
    "            st.success(\"Text Categorized as: {}\".format(prediction))\n",
    "\n",
    "# Required to let Streamlit instantiate our web app.  \n",
    "if __name__ == '__main__':\n",
    "\tmain()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
